name: single_sign_on
description: sso_signin is a package where user can add athentication using Google, Microsoft and LDAP.
version: 0.0.3
publish_to: 'https://github.com/coderidgetech/sso_signin.git'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  http: ^1.2.1
  webview_flutter: ^3.0.0
  fluttertoast: ^8.2.5
  another_flushbar: ^1.12.30
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.9
  pin_code_fields: ^8.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - lib/assets/

